### ISSUE TITLE
Get IP address from client/request

### ISSUE THREAD

**Issue by Nexulo** [OpenMarshal/npm-WebDAV-Server#117]
Is there any way to get the IP address of a request? I would like to block IP addresses so that no requests are possible at all.

**Comment by hironico** [comment]
Hi,

If you host your webdav server yourself, then I recommend to opt for a firewall and/or ip-table mechanism instead. 
This would ensure better security to your whole machine including your webdav server and will be far more robust to any kind of possible attack versus managing this yourself.

Some directions:

[Ubuntu iptables and firewall](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-22-04)

[Windows Firewall](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/best-practices-configuring)

Otherwise, if you really want to have this into your webdav server then you should setup a RequestListener like this: 

>  export const beforeRequestListener: RequestListener = (ctx, next) => {
>    // ctx is HTTPRequestContext type so you should inspect the ctx.request object, 
>    // in particular the host and headers properties 
>}

And register it into your server : 

> const server = new webdav.WebDAVServer({ ... });
> server.beforeRequest(beforeRequestListener);

**Remember that adding a request listener may cause performance problems and it should be used with caution, recommended approach is the firewall one for the requirement you describe.**

Hope this helps.

**Comment by Nexulo** [comment]
Hi and thank you for your help.

Unfortunately i cannot set up a firewall on my shared server. I solved this differently on my server.

Simply said, it is checked via rewrite in the .htaccess file, whether an IP file (/path/to/blocked/ips/xxx.xxx.xxx.xxx) exists. If yes, the access is denied.

And on my webdav server i did following:

```
const requestIp       = require('request-ip');

// ...

server.beforeRequest((ctx, next) => {
  const ipAddress = requestIp.getClientIp(ctx.request);
  // check if ip file exists
  if (systemFS.existsSync("/path/to/blocked/ips/"+ipAddress)) {
    //file exists
    console.info("WARNING - Blocked IP-Address: "+ipAddress)
    ctx.setCode(400); // Bad request
    ctx.exit();
  }
  else {
      next();
  }
})
```

**Comment by hironico** [comment]
Oh I see.

2 small remarks however : 
- existsSync usage may create a performance bottleneck by sync'ing the node event loop at every single request made to the server. This could be problematic if it serves plenty of small files at once for instance. I'd rather use a promise based version of this so that it can handle other requests concurrently.
- I would return a 403 forbidden response code which makes more sense to me. 

Anyway seems like we found something that works ! :-)
