### ISSUE TITLE
add a way to return json instead of xml

### ISSUE THREAD

**Issue by mnewmedia** [OpenMarshal/npm-WebDAV-Server#2]
Cool stuff, thanks for sharing! Maybe add a way to return json instead of xml?

**Comment by AdrienCastex** [comment]
Hello,

Returning JSON instead of XML would lead a little away from the [specification](http://www.webdav.org/specs/rfc4918.html), but I think it's a great idea.
I will add it to the tasks to do.

I guess, the best way to select the resulting langage (XML or JSON) is through the [HTTP Accept header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html).

Thank you @mnewmedia.

PS : I'm glad you like it.

**Comment by AdrienCastex** [comment]
You can now (`v0.4.0-alpha`) use JSON instead of XML with the HTTP header `Accept`.
For instance, with `request` in JavaScript :
```javascript
request({
    url: 'http://...',
    method: 'PROPFIND',
    headers: {
        Accept: 'application/json'
    }
}, (e, res, body) => {
    // ...
});
```
