### ISSUE TITLE
How it can be used in express.js or nuxt.js?

### ISSUE THREAD

**Issue by AlexRadch** [OpenMarshal/npm-WebDAV-Server#23]
I am writing nuxt app and want webDAV server for some url, for  example `http://my_app/users/someUser/files/webDAV` to open user files as webDav folder.

How `npm-WebDAV-Server` can be used to handle requests from nuxt or from express server. Handler have next api `handler(req, req, next)`.

**Comment by AdrienCastex** [comment]
Hello,

In order to easily use the WebDAV server in other servers, I exported the `executeRequest` function in the instance of the server. It is now (`v2.3.10`) possible to invoke the request/response process without starting the server.

For `Express`, you can do so :
```javascript
// TypeScript
import { v2 as webdav } from 'webdav-server'
import * as express from 'express'
// Javascript
const webdav = require('webdav-server').v2;
const express = require('express');

const server = new webdav.WebDAVServer();
const app = express();

// Root path
// This will allow '/my/sub/path/folder/file.txt' to give '/folder/file.txt'
// in the WebDAV server
const pathRegex = /^\/?my\/sub\/path((\/[^\/]+)*)\/?$/;
app.get(pathRegex, (req, res) => {
    const subUrl = pathRegex.exec(req.url)[1];

    // Set the sub path as the path of the request to point
    // to the right resource in the WebDAV server
    req.url = subUrl;

    // Execute the request in the WebDAV server
    server.executeRequest(req, res);
});

app.listen(1901); // Start the Express server
```

I don't know `Nuxt` enough to give a clear answer, sorry.

I hope that helped you. I let you close the issue if you think that I answered.

Thank you very much for your contribution.

**Comment by F145h** [comment]
Great feature, but during processing of all requests, PROPFIND's response contains name of parent directory

app.**all**(pathRegex, (req, res) => {
...
}

**Comment by AdrienCastex** [comment]
Hello,

You are right, using `app.all(...)` is better. I fixed the example in the `README.md`.

I upgraded the module (`v2.3.12`) to allow the use of a root path in the `executeRequest` method.

```javascript
// Root path
// This will allow '/my/sub/path/folder/file.txt' to give '/folder/file.txt'
// in the WebDAV server
const pathRegex = /^(\/my\/sub\/path)((\/[^\/]+)*)\/?$/;
app.all(pathRegex, (req, res) => {
    const matches = pathRegex.exec(req.url);
    const subUrl = matches[2];
    const root = matches[1]; // = '/my/sub/path'

    // Set the sub path as the path of the request to point
    // to the right resource in the WebDAV server
    req.url = subUrl;

    // Execute the request in the WebDAV server
    server.executeRequest(req, res, root);
});
```

Thank you very much for your contribution.

**Comment by F145h** [comment]
Great job, Amazing! Look at this express handler without the secondary same regexp matching:

const davHttpBase = "/webdav";
app.all(new RegExp("^(" + davHttpBase + ")((/[^/]+)*)/?$"), (req, res) => {
    req.url = req.url.substr(davHttpBase.length);
    davserver.executeRequest(req, res, davHttpBase);
});

It's more simple as for me, what do you think?

**Comment by AdrienCastex** [comment]
It is nice, but I finally made a easy-to-use function for this :

```javascript
const server = new webdav.WebDAVServer();
const app = express();

// Mount the WebDAVServer instance
app.use(webdav.extensions.express('/my/sub/path', server));
app.listen(1901); // Start the Express server
```

I was inspired by `express-static`.

**Comment by F145h** [comment]
Perfect solution!

**Comment by F145h** [comment]
When i use

`app.use(webdav.extensions.express('/webdav', server))`

have a problems with mounting drive in Windows 10 as http://localhost:1337/webdav/ (or http://localhost:1337/webdav). only subfolders(http://localhost:1337/webdav/s3/) are mounted well

To solve this need a patch in **webdav.extensions.express()**: 
`var path = new Path_1.Path(root).toString(false);`
endsWithSlash: **false** instead of true

What do you think?

**Comment by F145h** [comment]
Adrien, great, thank you for your support.

i have problem with Digest authentification with webdav over express:

`app.use(webdav.extensions.express('/webdav', server))`

in the method **HTTPDigestAuthentication.getUser**(...) **result** is not equal with **authProps.response**

`            if (result.toLowerCase() === authProps.response.toLowerCase())`

this is because value ctx.requested.uri is '/'(instead of '/webdav/')

**Comment by udanpe** [comment]
@AdrienCastex Can you explain how to use webdav.extensions.express with privilegeManager? 
In my case, unfortunately, credentials accepted only for root path
```
// Tt's ok (host: localhost, login: username, password: password)
const user = userManager.addUser('username', 'password', false);
app.use(webdav.extensions.express('/', server))

// Error 401 ((host: localhost/webdav, login: username, password: password))
const user = userManager.addUser('username', 'password', false);
app.use(webdav.extensions.express('/webdav', server))
```
