### ISSUE TITLE
custom FSManager, "Azure File storage" example

### ISSUE THREAD

**Issue by andreasgrimm** [OpenMarshal/npm-WebDAV-Server#3]
as the linked wiki page in (https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Persistence) regarding _the making of a custom FSManager_ is still a [To do](https://github.com/OpenMarshal/npm-WebDAV-Server/projects/3) I want to suggest the idea of an example of _Custom FSManager_ for "Azure File storage".

[edit] or maybe even better for "Azure Blob storage" (using maybe this one: https://www.npmjs.com/package/azure-storage-fs) or the like.

**Comment by AdrienCastex** [comment]
Hello,

I don't know Azure Blob storage and I don't have an Azure account, but if the [azure-storage-fs npm package](https://www.npmjs.com/package/azure-storage-fs) is working, then it sounds like the Azure Blob storage is pretty similar to a WebDAV storage, so I guess it can be relatively easy to create a custom `FSManager` and custom resources.

There are two ways to understand it :
* making WebDAV resources which link to the Azure resources.
* making a gateway to the Azure Blob storage server.

Because I don't have an Azure account, I cannot work on it (I will not be able to test it), but feel free to do it and ask me if you encounter any issue (on this thread or by email). I would say that it sounds similar to the `PhysicalFSManager` and the `PhysicalResource(s)` but instead of using `fs` maybe you can use `azure-storage-fs`.

On my side, I will work as soon as possible on the "custom" pages of the wiki to provide you (and others) more information on this subject.

Thank you for your interest in this project.

**Comment by andreasgrimm** [comment]
amazing :) thanks for your fast reply.

ok, I'll try to start with the `AzureBlobStorageFSManager` at some point and I'll keep you updated via this thread here.

**Comment by AdrienCastex** [comment]
I made a little starter file to help you.
You can find it at [https://gist.github.com/AdrienCastex/1bb0c4977f696639549d544afaa69faf](https://gist.github.com/AdrienCastex/1bb0c4977f696639549d544afaa69faf).

You will find inside the `ABSFSManager`, the `ABSFile`, the `ABSFolder` and the `ABSResource` (sharing methods for the `ABSFile` and `ABSFolder`).

`ABSFSManager` inherits from `FSManager`.
`ABSResource` inherits from `StandardResource` (which inherit from `IResource`).
`ABSFile` and `ABSFolder` inherit from `ABSResource`.

What I provided should not work (because nothing works the first try), but I guess it's a good start.
I hope it will help you.
