### ISSUE TITLE
Propfind - Depth:Infinity?

### ISSUE THREAD

**Issue by skoschik** [OpenMarshal/npm-WebDAV-Server#48]
Wondering if this library supports a depth header = 'Infinity' for Propfind requests?  A real quick browsing through the code here and I didn't come across anything for depth headers on propfind requests ( i see for deletes and moves etc).

**Comment by AdrienCastex** [comment]
Hello,

Yes, it handles the depth value `infinity` (not case sensitive). It also interpret the negative values as infinity.
But if you find a case it doesn't, let us know.

If you want to know where is it handled in the code, you can find it at the line 29 in the file `src\server\v2\RequestContext.ts`, in the class `RequestContextHeaders`.

**Comment by AdrienCastex** [comment]
Hello,

The feature is now available on the version `2.4.3` (current version on npm).

In order to enable Infinity values, you have to set the server's option `maxRequestDepth` to `-1` or `Infinity` (the JS number, not the string). [Updated documentation](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Server's-options-and-customizations-%5Bv2%5D).

Thank you very much for your contribution.
