### ISSUE TITLE
Uploading a file with .url in the name breaks directory listing

### ISSUE THREAD

**Issue by SpudNyk** [OpenMarshal/npm-WebDAV-Server#59]
I uploaded a file with .url in the name (`test.urlfile.txt`) and the directory listing immediately broke.

I noticed the following lines in v2 PhysicalFileSystem method _type. 

```
        if(realPath.indexOf('.url') !== -1)
            return callback(Errors.ResourceNotFound);
```

Implementing my own filesystem inheriting from PhysicalFileSystem and reimplementing the _type method to not include those lines, fixed my issue.

But I am curious as to why those lines are there, in the first place, as it seems like a bug.

**Comment by AdrienCastex** [comment]
Hello,

Indeed, this should not be there. It was, for sure, an early project to make the '.url' resources behave like directories linking to another webdav resource. This special case is removed because it must not exist in this class.

The fact that it is breaking the listing is because of another bug in the PROPFIND code.

Both are fixed in the version `1.5.1`.
Thank you very much for your contribution.
