### ISSUE TITLE
Gateway implementation

### ISSUE THREAD

**Issue by fentas** [OpenMarshal/npm-WebDAV-Server#8]
I got the repo to work for VirtualFolder/File but for my use case I need
> processed/computed resources (for instance a file which provides the content of a remote web page)

I can't load these files in memory. Would be too much. Need lazy load.
Do have an example for this?

Thanks a lot.

**Comment by AdrienCastex** [comment]
Hello,

You can find here an [example of a custom resource/file manager which get its content from the web](https://github.com/OpenMarshal/npm-WebDAV-Server/tree/master/examples/customWebResource).

You can find more information about [custom resources here](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Custom-resources).

*Note 1 :* The file manager is optional if you don't expect to serialize/unserialize the state of the server and if you only have files.

*Note 2 :* It is possible to use a `VirtualFolder` instead of a custom folder if its behavior is the same. You will just need to specify that the `fsManager` of the `VirtualFolder` is your custom `FSManager` :
```javascript
new webdav.VirtualFolder('folderName', null /* or parent */, myFSManagerInstance);
```

I hope that helped you.
If you encounter some troubles while making your own resource/file manager, do not hesitate to ask for help. You can ask here or on the brand new [Gitter](https://gitter.im/npm-WebDAV-Server/Lobby).

I let you close the issue if you feel that I answered your question.

Thank you very much for you interest.

**Comment by fentas** [comment]
You are awesome. :+1: 
I also created a WebFolder, same as File with `StandardResource` because I got a restful endpoint which also representing a folder structure.
As for now, everything works as expected :sparkles: 

If you do not mind I have only two more questions for now.
- I guess `newResource` within `WebFSManager` is for creating new Ressources (Files/Directories). But where I have to register it (WebFSManager)? I figure that I can't use the autoLoad/Save functionality because depending on authorization headers I deliver different content. I tried `webdav.load(null, [...])` with no luck.
- For now, I load the whole file/folder structure on startup. But for future use, if I want to lazy load contents I would use `server.beforeRequest` and depending on `arg.uri` I would load the specified folder, wouldn't I? (what's is the difference to invokeBeforeRequest?)

Thanks. For more questions I will use Gitter. :100:

**Comment by fentas** [comment]
I will use Gitter. I have more questions. Thanks a lot!

**Comment by AdrienCastex** [comment]
### Answers

> But where I have to register it (WebFSManager)?

Your `WebFSManager` needs to be registered in the resources itself (in the property `fsManager`, but the constructor of `webdav.StandardResource` already store it in this property, so it is enough).

> [...] but `newResource` never gets triggered

It is triggered when the server needs to create a new resource in the case of `PUT`, `POST`, `LOCK`, `MKCOL` requests made on a resource which doesn't exist. In this case, the server will ask to the parent's `fsManager` (for `/folder1/folder2/file.txt`, it will use the `fsManager` of `/folder1/folder2`) and call its method `newResource(...)`. Depending on the request, it will ask to create a file resource or a folder resource. This method will create a new resource based on this type and must not call anything on these resource. If you need to send a request to your remote server to say : "I create a new resource", implement this behavior in the `create(...)` method of your resource. When you add a resource through the `addResourceTree(...)` method, for instance, it calls nothing else than `addChild(...)`.

> I figure that I can't use the autoLoad/Save functionality because depending on authorization headers I deliver different content.

You can use persistence but without storing the content of your resources, just the properties, etc...

> I would use `server.beforeRequest` and depending on `arg.uri` I would load the specified folder, wouldn't I?

Except if you have only one user on your server, you will load have concurrency with the loaded folders.

> what's is the difference to invokeBeforeRequest?

`invokeBeforeRequest` just call the functions registered through the `beforeRequest(...)` method. It is an internal method and is not intended to be used by anyone else than the server itself.

### Gateway

If I understand, your restful server provides you a tree of folders/files which depends on the user authenticated on the current request. So, if I'm right, you will need a new concept : the Gateway. I was planning to implement it, but I was thinking about the best way to do it. I believe it will fit exactly your needs.

The aim of the gateway is to provide, based on the requested URL, the request headers and the user, a sub-tree of resources. For instance, the request '/folder1/folder2' is a gateway, then when requesting '/folder1/folder2/folder3/file1', the server will not use the linear way to find a resource based on the URL but will delegate the finding of `/folder3/file1` to `/folder1/folder2`. That's the interaction between the server and a gateway. So, this way, your gateway resource can provide a different `/folder3/file1` instance depending on the request (URL, headers and user).

The gateway is not implemented yet, but I make it my priority because I believe it will be awesome and fit your needs.

**Comment by fentas** [comment]
Gateway is what I need. :+1: 
I guess I'll reopen the issue.

**Comment by fentas** [comment]
Will close due to the latest release. :+1: 
Will reopen if problems occur.
