### ISSUE TITLE
How to use real folders and files

### ISSUE THREAD

**Issue by yueduz** [OpenMarshal/npm-WebDAV-Server#9]

**Comment by AdrienCastex** [comment]
Hello, you can do this way :

```javascript
// TypeScript
import { v2 as webdav } from 'webdav-server'
// Javascript
const webdav = require('webdav-server').v2;

const server = new webdav.WebDAVServer();
server.setFileSystem('/physicalFolder', new webdav.PhysicalFileSystem('/my/path/to/the/folder'), (success) => {
    server.start(() => console.log('READY'));
})
```

**Comment by yueduz** [comment]
Useless

Adrien Castex <notifications@github.com>于2017年7月24日周一 下午11:20写道：

**Comment by AdrienCastex** [comment]
Explain more, give details, otherwise I can't help you.

What do you mean by "useless"?
What are you unable to do? (if there is)
What don't you understand in the sample I provided? (if there is)

The sample I provided map the "real" folder `/my/path/to/the/folder` into the server's path `/physicalFolder`.

**Comment by yueduz** [comment]
I don't see the folder being created, I use jsdav instead, thank you for your help.

**Comment by yueduz** [comment]
The example has been running and thank you very much.
